# .forge-lock.hcl — DO NOT EDIT MANUALLY
# Generated by forge. Changes will be overwritten on sync.

blueprint {
  registry_url = "/Users/donaldgifford/code/forge-registry"
  name         = "go-cli"
  path         = "go/cli"
}

created_at    = "2026-07-29T15:27:17.837839Z"
last_synced   = "2026-07-29T15:27:17.837839Z"
forge_version = "0.7.0"

variables {
  git_host                    = "github.com"
  git_provider                = "github"
  go_version                  = "1.26.5"
  license                     = "Apache-2.0"
  project_component_lifecycle = "production"
  project_component_owner     = "donaldgifford"
  project_component_system    = "dev-tools"
  project_component_type      = "service"
  project_description         = "A Go CLI tool for managing security champions"
  project_name                = "champs"
  project_org                 = "donaldgifford"
  project_owner               = "donaldgifford"
  renovate_config_prefix      = "github"
}

default ".claude/settings.json" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:f0bd8bd9ee7e8771c4384fb065a16977e5006803b3eb01a8a06d0246476cac90"
}

default ".docz.yaml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:f3fb2387d31e3b07fa2a1efdf3e974814b13113c763a7b82d7425eb2967bbcfc"
}

default ".github/CODEOWNERS" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:666453f28d6c351868d33031fd710f5ebab775b7dab797694b23eb587e161a4a"
}

default ".github/actionlint.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:4116d94fbad5355f4422bd9db3d7f1ba28126cb017f1125f6e55af967dc5b7bb"
}

default ".github/labeler.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:d3b1b43336e037755731eb3f11a1d61a066429ce87078a566a1db89f92031975"
}

default ".github/licenses-csv.tpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:181b0c267bcc0c99b7e448de827c3a9a6c65ac4e2755d2529b9985018929b2f7"
}

default ".github/workflows/changelog-regen.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:224de5161f409a9a621ba7c26af352cf7b204e7a6de4307b0150c9941db38b69"
}

default ".github/workflows/changelog.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:364e27010334331c58e86fce64b94fdcbd8a22003e31765847017f07e468faf8"
}

default ".github/workflows/ci.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:d2fd347e45e57293ca2cdac030766a1992a95df34145ac4a114e337a44b2bf4c"
}

default ".github/workflows/pr-labels.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:1789341a42632af6acb115ede669f0f215e3b6f2a19a44107e352c4a556be2bd"
}

default ".github/workflows/release.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:01346219b30cc4d4e9f578487c3ec59f4568a97a9b48cb45973fd8da33aa00ee"
}

default ".github/workflows/trufflehog.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:d4cf9e0b23080af692c78073cc6052102de605db33539d0e3940e7fc4b25ca72"
}

default ".gitignore" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:2ade0572a141b09f93c32c355d9f51a12f535feeb449979554e11c8fa0845a5a"
}

default ".markdownlint.yaml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:c109f82759d9451b3060f5e8e1cb07752aca359faea7bc6057e61dd7eb7f20b7"
}

default ".prettierrc.yaml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:265dc1424b9b6aeb0edab3e6a0e60302b7595a3fa2feb0c4656458967b841d23"
}

default ".yamlfmt.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:731740b1cb919db6cb1c7e26caafc4902a5a0d8d16729ac698227192b40ae473"
}

default ".yamllint.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:a472c9461a2a585d3915658b96f65e6b89cbea9c4f2c9650083f0db5bc6b4c1a"
}

default "CONTRIBUTING.md.tmpl" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:77bccaa0f89f476318a459d82eaf03f0da99871fbdc790ca6341dc20a4fafc75"
}

default "README.md.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:d9cf02f2711ac14cfef4bbd562548638bc34ea6a423e8633619042ab988ce3e0"
}

default "catalog-info.yaml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:62cae2a995464de4cedaa504dbfba154ff919acdeb41e0f2a9eb5545f9ebe564"
}

default "justfile.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:2e88f471ec82cae07e422b00c056a3f5942768586bfbf07746b5bc7a492a3dcb"
}

default "mise.toml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:324163376cd7400ad0c01a60409c2b628614a76f84f450a5b72069adc277c2d3"
}

default "renovate.json5.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:15f4007ddcaa61259c275a55d0587b73d610f7a7e1bab6351518c61c962e280a"
}

default "scripts/labels.sh" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:9a67e59fc7ea35194415b9ad246d14cc3296aa1a588d01a24ac7ea7784ecdcb3"
}

default ".codecov.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:7fd3a5708d6399810e2fb497afe6fa03000119ebb2acdf09fd5b1f1095d84f3a"
}

default ".github/dependabot.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:686e64698b4f287695b9ffe55e6b71b88bac4c199b929b1916543b58429b7d47"
}

default ".github/workflows/codeql.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:5ffbf6721ed9f3e7e0289798e6a79aca8913fbd0ec6b48508a6bcace62e2697c"
}

default ".github/workflows/dependabot-severity-label.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:331019181284ad68d156474cb7fd3ffe17453943d68b6e76df0f5c931481a6cc"
}

default ".github/workflows/license-check.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:fdbc23ba9b8bf9c962bfc492acd98806018d845c212534519c4a0ef81e8dad23"
}

default ".github/workflows/security.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:a8e9146925097d1c9b0049014c299c021a5dfab73322864a2019447f85500f38"
}

default ".golangci.yml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:57d9bfb542912e3507eeff1431affe3b0e1e088f8ed69d4d4143f18dcf660dd5"
}

default ".goreleaser.yml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:3fef2e18412bf758f102b4e3750be2d362802aaa7923b9b18b46e636bc73a009"
}

default "CHANGELOG.md" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:b64a7868c1db77e87d899af1d46c8c12d19a8c39d0b3b9a43753f75c1a0718aa"
}

default "CLAUDE.md.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:c6657be573edd5dc80f7f68261ef47c0229d7bb119bfdf098de4e40cd275c7d1"
}

default "Makefile.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:8a7229382cf97084081e37854770e3821685ebc6e3ddde22b9fd68ffa685543d"
}

default "cliff.toml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:6bad4c1c62f234682236da0b4ab231abb121d64652fbc8402f7949c68b704186"
}

default "cmd/$${project_name}/main.go.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
}

default "go.mod.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:8b3586fce9e0bd191ff857e0e30d23bef7d5555af90bbbb51285d9cc6bbf961d"
}

default "internal/.gitkeep" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
}
